# Generated by Django 4.0.6 on 2023-09-03 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_citizen_rename_companieslist_companies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abouttrees',
            name='filterName',
            field=models.CharField(default=12, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abouttrees',
            name='region',
            field=models.CharField(choices=[('TSH', 'Toshkent Shahar'), ('TV', 'Toshkent Viloyati'), ('FR', "Farg'ona"), ('AD', 'Andijon'), ('NM', 'Namangan'), ('JZ', 'Jizzax'), ('SR', 'Sirdaryo'), ('SM', 'Samarqand'), ('BX', 'Buxoro'), ('XR', 'Xorazm'), ('NV', 'Navoiy'), ('QR', 'Qoraqolpoq'), ('SX', 'Surxondaryo'), ('QSH', 'Qashqadaryo')], default='TSH', max_length=3),
        ),
        migrations.CreateModel(
            name='UserTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('treeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.abouttrees')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.citizen')),
            ],
        ),
    ]
