# Generated by Django 4.0.6 on 2023-09-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_abouttrees_filtername_abouttrees_region_usertree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttrees',
            name='image',
            field=models.ImageField(blank=True, upload_to='trees/img/'),
        ),
        migrations.AlterField(
            model_name='abouttrees',
            name='image1',
            field=models.ImageField(blank=True, upload_to='trees/img/'),
        ),
        migrations.AlterField(
            model_name='abouttrees',
            name='image2',
            field=models.ImageField(blank=True, upload_to='trees/img/'),
        ),
        migrations.AlterField(
            model_name='abouttrees',
            name='image3',
            field=models.ImageField(blank=True, upload_to='trees/img/'),
        ),
        migrations.AlterField(
            model_name='abouttrees',
            name='image4',
            field=models.ImageField(blank=True, upload_to='trees/img/'),
        ),
    ]
