# Generated by Django 4.0.6 on 2023-09-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_abouttrees_image_alter_abouttrees_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttrees',
            name='filterName',
            field=models.CharField(choices=[('MB', 'Manzalari butalar'), ('YP', 'Yaproq bargli'), ('MV', 'Mevali daraxtlari'), ('MN', 'Manzalari Ninabarg')], default='MN', max_length=3),
        ),
    ]
