# Generated by Django 4.0.6 on 2023-09-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_abouttrees_filtername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abouttrees',
            name='growing',
        ),
        migrations.RemoveField(
            model_name='abouttrees',
            name='regionImage',
        ),
    ]
