# Generated by Django 4.0.6 on 2023-09-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_abouttrees_growing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouttrees',
            name='region',
            field=models.CharField(choices=[('ALL', 'Barchasi'), ('TSH', 'Toshkent Shahar'), ('TV', 'Toshkent Viloyati'), ('FR', "Farg'ona"), ('AD', 'Andijon'), ('NM', 'Namangan'), ('JZ', 'Jizzax'), ('SR', 'Sirdaryo'), ('SM', 'Samarqand'), ('BX', 'Buxoro'), ('XR', 'Xorazm'), ('NV', 'Navoiy'), ('QR', 'Qoraqolpoq'), ('SX', 'Surxondaryo'), ('QSH', 'Qashqadaryo')], default='TSH', max_length=3),
        ),
    ]
